version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/your_db_name
    depends_on:
      - mongo

  frontend:
    build:
      context: ./django
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    environment:
      - DEBUG=1
    depends_on:
      - backend

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
